package com.app.core.navigation

object AppRoutes {
    const val Splash = "splash"
    const val Login = "login"
    const val WalletGuide = "wallet_guide"
    const val WalletHome = "wallet_home"
    const val NodeList = "node_list"
    const val PlanList = "plan_list"
    const val AssetList = "asset_list"
    const val TokenDetailPattern = "token_detail/{symbol}"
    const val SendPattern = "send/{symbol}"
    const val ReceivePattern = "receive/{symbol}"
    const val WalletPaymentConfirmPattern = "wallet_payment_confirm/{orderId}"

    const val ForceUpdate = "force_update"
    const val VersionUpdate = "version_update"
    const val Register = "register"
    const val ResetPassword = "reset_password"
    const val VpnHome = "vpn_home"
    const val OrderPaymentPattern = "order_payment/{orderId}"
    const val OrderResultPattern = "order_result/{orderId}"
    const val OrdersCenter = "orders_center"
    const val OrderDetailPattern = "order_detail/{orderId}"
    const val SendResultPattern = "send_result/{txId}"
    const val InviteCenter = "invite_center"
    const val CommissionLedger = "commission_ledger"
    const val WithdrawCommission = "withdraw_commission"
    const val Profile = "profile"
    const val EffectLab = "effect_lab"
    const val HeaderRingLab = "header_ring_lab"
    const val LegalDocuments = "legal_documents"
    const val LegalDetailPattern = "legal_detail/{docId}"

    const val ImportWallet = "import_wallet"
    const val InputMnemonic = "input_mnemonic"
    const val BackupMnemonic = "backup_mnemonic"
    const val VerifyMnemonic = "verify_mnemonic"
    const val SecurityCenter = "security_center"
    const val ChainManager = "chain_manager"
    const val AddCustomToken = "add_custom_token"
    const val Swap = "swap"
    const val Bridge = "bridge"
    const val DappBrowser = "dapp_browser"
    const val WalletConnect = "wallet_connect"
    const val SignRequestPattern = "sign_request/{requestId}"

    const val MarketOverview = "market_overview"
    const val MarketTickerDetailPattern = "market_ticker_detail/{symbol}"

    const val NodeDetailPattern = "node_detail/{nodeId}"
    const val Subscription = "subscription"
    const val OrderPattern = "order/{planId}"

    val topLevelRoutes = setOf(WalletHome, VpnHome, MarketOverview, Profile)

    fun tokenDetail(symbol: String) = "token_detail/$symbol"
    fun send(symbol: String) = "send/$symbol"
    fun receive(symbol: String) = "receive/$symbol"
    fun walletPaymentConfirm(orderId: String) = "wallet_payment_confirm/$orderId"
    fun orderPayment(orderId: String) = "order_payment/$orderId"
    fun orderResult(orderId: String) = "order_result/$orderId"
    fun orderDetail(orderId: String) = "order_detail/$orderId"
    fun sendResult(txId: String) = "send_result/$txId"
    fun legalDetail(docId: String) = "legal_detail/$docId"
    fun signRequest(requestId: String) = "sign_request/$requestId"
    fun marketTickerDetail(symbol: String) = "market_ticker_detail/$symbol"
    fun nodeDetail(nodeId: String) = "node_detail/$nodeId"
    fun order(planId: String) = "order/$planId"
}
