package com.app.feature.settings.ui

import androidx.compose.ui.graphics.Color

data class PalettePreviewPalette(
    val id: String,
    val title: String,
    val summary: String,
    val bestFor: String,
    val moduleAccent: String,
    val rolloutNote: String,
    val colors: PalettePreviewColors,
)

data class PalettePreviewColors(
    val canvasTop: Color,
    val canvasBottom: Color,
    val glowPrimary: Color,
    val glowSecondary: Color,
    val frameBorder: Color,
    val shellTop: Color,
    val shellBottom: Color,
    val title: Color,
    val body: Color,
    val quiet: Color,
    val accentStart: Color,
    val accentEnd: Color,
    val accentSoft: Color,
    val accentText: Color,
    val positive: Color,
    val warning: Color,
    val chartLine: Color,
    val chartFill: Color,
)

val PalettePreviewPalettes = listOf(
    PalettePreviewPalette(
        id = "glacier",
        title = "A1 冰川蓝",
        summary = "最接近当前轻科技主方向，信息层级稳，适合先做低风险试点。",
        bestFor = "钱包首页、资产总览、通用 Dashboard。",
        moduleAccent = "让主指标和关键操作保持蓝青渐变，辅助模块尽量收敛。",
        rolloutNote = "如果只能先试一个方向，优先从它开始。",
        colors = PalettePreviewColors(
            canvasTop = Color(0xFFF8FBFF),
            canvasBottom = Color(0xFFEEF5FF),
            glowPrimary = Color(0x334F7CFF),
            glowSecondary = Color(0x2425D7FF),
            frameBorder = Color(0x26A5C3FF),
            shellTop = Color(0xFFFFFFFF),
            shellBottom = Color(0xFFF4F9FF),
            title = Color(0xFF142845),
            body = Color(0xFF57709A),
            quiet = Color(0xFF8A9AB6),
            accentStart = Color(0xFF4F7CFF),
            accentEnd = Color(0xFF25D7FF),
            accentSoft = Color(0xFFEAF3FF),
            accentText = Color.White,
            positive = Color(0xFF19C392),
            warning = Color(0xFFFFB44F),
            chartLine = Color(0xFF4F7CFF),
            chartFill = Color(0xFF7FDFFF),
        ),
    ),
    PalettePreviewPalette(
        id = "harbor",
        title = "A2 港湾薄荷",
        summary = "把主层从纯蓝冷调转成青绿金融感，更柔和，也更像服务型总览。",
        bestFor = "VPN 首页、节点概览、状态中枢类页面。",
        moduleAccent = "模块卡片和状态点用薄荷色强调，减少连续大面积强蓝。",
        rolloutNote = "适合想保留科技感，但不想太像交易页的方向。",
        colors = PalettePreviewColors(
            canvasTop = Color(0xFFF6FFFD),
            canvasBottom = Color(0xFFEAF8F4),
            glowPrimary = Color(0x3322C89B),
            glowSecondary = Color(0x224A7BFF),
            frameBorder = Color(0x2692D4C3),
            shellTop = Color(0xFFFFFFFF),
            shellBottom = Color(0xFFF1FBF8),
            title = Color(0xFF163347),
            body = Color(0xFF4D6E73),
            quiet = Color(0xFF83989A),
            accentStart = Color(0xFF177F82),
            accentEnd = Color(0xFF42D5B1),
            accentSoft = Color(0xFFE6FFF7),
            accentText = Color.White,
            positive = Color(0xFF12B881),
            warning = Color(0xFFFFB565),
            chartLine = Color(0xFF19959A),
            chartFill = Color(0xFF87E6CB),
        ),
    ),
    PalettePreviewPalette(
        id = "signal",
        title = "A3 信号珊瑚",
        summary = "保留冷静底盘，用珊瑚橙做模块 accent，重点更强，更适合运营型面板。",
        bestFor = "增长看板、风控页、需要强调模块分区的组合首页。",
        moduleAccent = "CTA、活跃指标和模块标签能更醒目，但要克制暖色占比。",
        rolloutNote = "它最有辨识度，也最需要真机确认是否过热。",
        colors = PalettePreviewColors(
            canvasTop = Color(0xFFFFFCFA),
            canvasBottom = Color(0xFFFFF1EA),
            glowPrimary = Color(0x33FF9A63),
            glowSecondary = Color(0x224B63FF),
            frameBorder = Color(0x26FFB78A),
            shellTop = Color(0xFFFFFFFF),
            shellBottom = Color(0xFFFFF6F2),
            title = Color(0xFF232A40),
            body = Color(0xFF6A6178),
            quiet = Color(0xFF978DA0),
            accentStart = Color(0xFF4C60FF),
            accentEnd = Color(0xFFFF8C5B),
            accentSoft = Color(0xFFFFEFE6),
            accentText = Color.White,
            positive = Color(0xFF1EB98B),
            warning = Color(0xFFFFA648),
            chartLine = Color(0xFF5B6BFF),
            chartFill = Color(0xFFFFBA8C),
        ),
    ),
)
