#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib.sh"

usage() {
  cat <<USAGE
usage: dispatch-kimi.sh [--driver cli|stub] [--timeout-sec N] [--stub-change PATH] <task-yaml>
USAGE
}

DRIVER="cli"
TIMEOUT_SEC=120
STUB_CHANGE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --driver)
      DRIVER="${2:?missing value for --driver}"; shift 2 ;;
    --timeout-sec)
      TIMEOUT_SEC="${2:?missing value for --timeout-sec}"; shift 2 ;;
    --stub-change)
      STUB_CHANGE="${2:?missing value for --stub-change}"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    --)
      shift; break ;;
    -*)
      echo "[ERR] unknown option: $1" >&2
      usage
      exit 1 ;;
    *)
      break ;;
  esac
done

TASK_FILE_INPUT="${1:?missing task-yaml}"
TASK_FILE="$(task_file_abs "$TASK_FILE_INPUT")"

require_cmd git
require_cmd python3

if [[ "$DRIVER" == "cli" ]]; then
  require_cmd expect
  require_cmd kimi
fi

ROOT="$(git_root)"
PROOT="$(project_root)"
PROJ_SUBDIR="$(project_subdir_from_git_root)"
TASK_ID="$(task_id_from_yaml "$TASK_FILE")"
KIMI_WT_REL="$(worktree_from_yaml "$TASK_FILE")"
KIMI_WT_ABS="$(resolve_from_git_root "$KIMI_WT_REL")"
ART_DIR_ABS="$(artifacts_abs_from_task "$TASK_ID")"
ART_DIR_REL="$(artifacts_rel_from_task "$TASK_ID")"
PROMPT_FILE="$ART_DIR_ABS/prompt.txt"
LOG_FILE="$ART_DIR_ABS/kimi-dispatch.log"

if [[ ! -d "$KIMI_WT_ABS" ]]; then
  echo "[ERR] kimi worktree not found: $KIMI_WT_ABS" >&2
  exit 1
fi

mkdir -p "$ART_DIR_ABS"

ALLOW_LINES="$(yaml_get_list allow "$TASK_FILE" | sed 's/^/- /')"
DENY_LINES="$(yaml_get_list deny "$TASK_FILE" | sed 's/^/- /')"
COMMANDS_LINES="$(yaml_get_list commands "$TASK_FILE" | sed 's/^/- /')"
DELIVERABLES_LINES="$(yaml_get_list deliverables "$TASK_FILE" | sed 's/^/- /')"
GOAL="$(yaml_get_scalar goal "$TASK_FILE")"
COMMIT_MSG="$(yaml_get_scalar commit_message "$TASK_FILE")"
[[ -z "$COMMIT_MSG" ]] && COMMIT_MSG="feat(kimi): ${TASK_ID}"

cat > "$PROMPT_FILE" <<PROMPT
你是 Kimi worker。你在独立 worktree 中工作。

Task: ${TASK_ID}
Goal:
${GOAL}

项目相对仓库根路径：${PROJ_SUBDIR}
请优先在该项目目录内执行构建与测试命令。

Allowed paths:
${ALLOW_LINES:-- (none)}

Denied paths:
${DENY_LINES:-- (none)}

必须遵守：
1. 严禁修改 deny 列表中的文件。
2. 仅在 allow 列表范围内修改。
3. 完成后必须执行 commands 列表。
4. 产出并写入 deliverables 列表：
${DELIVERABLES_LINES:-- .parallel/artifacts/${TASK_ID}/handoff.md}
5. changed-files.txt 内容请使用 `git diff --name-only`。
6. commands-run.txt 记录你实际运行过的命令（含目录）。
7. 完成后执行：
   - git status --short
   - git add .
   - git commit --no-verify -m "${COMMIT_MSG}"

commands:
${COMMANDS_LINES:-- (none)}

任务单原文：
$(cat "$TASK_FILE")
PROMPT

if [[ "$DRIVER" == "stub" ]]; then
  echo "[INFO] running stub driver in $KIMI_WT_ABS" | tee "$LOG_FILE"
  mkdir -p "$KIMI_WT_ABS/$ART_DIR_REL"
  {
    echo "driver=stub"
    echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "task_id=$TASK_ID"
  } > "$KIMI_WT_ABS/$ART_DIR_REL/commands-run.txt"

  if [[ -n "$STUB_CHANGE" ]]; then
    mkdir -p "$(dirname "$KIMI_WT_ABS/$STUB_CHANGE")"
    printf '# %s\n\nGenerated by dispatch-kimi.sh --driver stub\n' "$TASK_ID" > "$KIMI_WT_ABS/$STUB_CHANGE"
  fi

  git -C "$KIMI_WT_ABS" diff --name-only > "$KIMI_WT_ABS/$ART_DIR_REL/changed-files.txt" || true
  cat > "$KIMI_WT_ABS/$ART_DIR_REL/test-report.txt" <<TXT
stub: no real test executed
TXT
  cat > "$KIMI_WT_ABS/$ART_DIR_REL/handoff.md" <<MD
# ${TASK_ID}
## Summary
- Stub execution completed by orchestrator for pipeline smoke test.
## Files Changed
- See changed-files.txt
## Commands Run
- See commands-run.txt
## Test Results
- stub mode only
## Risks
- Real Kimi CLI not invoked in stub mode.
MD

  git -C "$KIMI_WT_ABS" add "$ART_DIR_REL" ${STUB_CHANGE:+"$STUB_CHANGE"}
  if ! git -C "$KIMI_WT_ABS" diff --cached --quiet; then
    git -C "$KIMI_WT_ABS" commit --no-verify -m "chore(kimi-stub): ${TASK_ID} stub output"
  else
    echo "[WARN] nothing to commit in stub mode" | tee -a "$LOG_FILE"
  fi

  echo "[OK] stub dispatch finished" | tee -a "$LOG_FILE"
  exit 0
fi

echo "[INFO] dispatching Kimi CLI task in $KIMI_WT_ABS" | tee "$LOG_FILE"
expect "$(dirname "$0")/run-kimi-task.expect" "$KIMI_WT_ABS" "$PROMPT_FILE" "$TIMEOUT_SEC" "$ART_DIR_REL" "$(command -v kimi)" | tee -a "$LOG_FILE"

echo "[OK] task dispatched" | tee -a "$LOG_FILE"
