"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2026-03-29 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # plans table
    op.create_table(
        'plans',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('code', sa.String(32), unique=True, nullable=False),
        sa.Column('name', sa.String(128), nullable=False),
        sa.Column('description', sa.String(512), default=''),
        sa.Column('traffic_bytes', sa.BigInteger, nullable=False),
        sa.Column('duration_days', sa.Integer, nullable=False),
        sa.Column('price_usd', sa.Numeric(10, 2), nullable=False),
        sa.Column('supported_assets', sa.JSON, default=['SOL', 'USDT_TRC20']),
        sa.Column('enabled', sa.Boolean, default=True),
        sa.Column('sort_order', sa.Integer, default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    op.create_index('idx_plans_code', 'plans', ['code'])
    op.create_index('idx_plans_enabled', 'plans', ['enabled'])
    
    # orders table
    op.create_table(
        'orders',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('order_no', sa.String(32), unique=True, nullable=False),
        sa.Column('purchase_type', sa.String(10), nullable=False),
        sa.Column('plan_id', sa.String(32), sa.ForeignKey('plans.id'), nullable=False),
        sa.Column('client_user_id', sa.String(32), nullable=True),
        sa.Column('marzban_username', sa.String(64), nullable=True),
        sa.Column('chain', sa.String(20), nullable=False),
        sa.Column('asset_code', sa.String(20), nullable=False),
        sa.Column('receive_address', sa.String(64), nullable=False),
        sa.Column('amount_crypto', sa.Numeric(36, 18), nullable=False),
        sa.Column('amount_usd_locked', sa.Numeric(10, 2), nullable=False),
        sa.Column('fx_rate_locked', sa.Numeric(18, 8), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, default='pending_payment'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('tx_hash', sa.String(128), unique=True, nullable=True),
        sa.Column('tx_from', sa.String(64), nullable=True),
        sa.Column('confirm_count', sa.Integer, default=0),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('client_device_id', sa.String(64), nullable=False),
        sa.Column('client_version', sa.String(16), nullable=False),
        sa.Column('error_code', sa.String(32), nullable=True),
        sa.Column('error_message', sa.String(256), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    op.create_index('idx_orders_order_no', 'orders', ['order_no'])
    op.create_index('idx_orders_status', 'orders', ['status'])
    op.create_index('idx_orders_marzban_username', 'orders', ['marzban_username'])
    op.create_index('idx_orders_device_id', 'orders', ['client_device_id'])
    op.create_index('idx_orders_address', 'orders', ['receive_address'])
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'])
    op.create_index('idx_orders_tx_hash', 'orders', ['tx_hash'])
    
    # payment_addresses table
    op.create_table(
        'payment_addresses',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('chain', sa.String(20), nullable=False),
        sa.Column('asset_code', sa.String(20), nullable=False),
        sa.Column('address', sa.String(64), unique=True, nullable=False),
        sa.Column('encrypted_private_key', sa.String(512), nullable=True),
        sa.Column('status', sa.String(20), default='available'),
        sa.Column('allocated_order_id', sa.String(32), sa.ForeignKey('orders.id'), nullable=True),
        sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen_tx_hash', sa.String(128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    op.create_index('idx_payment_addr_chain', 'payment_addresses', ['chain'])
    op.create_index('idx_payment_addr_status', 'payment_addresses', ['status'])
    op.create_index('idx_payment_addr_address', 'payment_addresses', ['address'])
    
    # client_sessions table
    op.create_table(
        'client_sessions',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('order_id', sa.String(32), sa.ForeignKey('orders.id'), nullable=False),
        sa.Column('marzban_username', sa.String(64), nullable=False),
        sa.Column('access_token', sa.String(512), nullable=False),
        sa.Column('refresh_token', sa.String(512), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('idx_client_sessions_username', 'client_sessions', ['marzban_username'])
    op.create_index('idx_client_sessions_expires', 'client_sessions', ['expires_at'])
    
    # audit_logs table
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('entity_type', sa.String(32), nullable=False),
        sa.Column('entity_id', sa.String(32), nullable=False),
        sa.Column('action', sa.String(64), nullable=False),
        sa.Column('operator_type', sa.String(20), nullable=False),
        sa.Column('operator_id', sa.String(64), nullable=True),
        sa.Column('payload_json', sa.Text, nullable=True),
        sa.Column('client_ip', sa.String(64), nullable=True),
        sa.Column('user_agent', sa.String(512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'])
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'])
    
    # Insert default plans
    op.bulk_insert(
        'plans',
        [
            {
                'id': 'plan_monthly_100g',
                'code': 'monthly_100g',
                'name': '月度套餐 100GB',
                'description': '100GB流量，30天有效期，美国/日本/新加坡节点',
                'traffic_bytes': 107374182400,
                'duration_days': 30,
                'price_usd': 5.00,
                'supported_assets': ['SOL', 'USDT_TRC20'],
                'enabled': True,
                'sort_order': 1,
            },
            {
                'id': 'plan_yearly_1t',
                'code': 'yearly_1t',
                'name': '年度套餐 1TB',
                'description': '1TB流量，365天有效期，全节点',
                'traffic_bytes': 1099511627776,
                'duration_days': 365,
                'price_usd': 45.00,
                'supported_assets': ['SOL', 'USDT_TRC20'],
                'enabled': True,
                'sort_order': 2,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('client_sessions')
    op.drop_table('payment_addresses')
    op.drop_table('orders')
    op.drop_table('plans')
    # ### end Alembic commands ###
