"""Add user authentication system

Revision ID: 002
Revises: 001
Create Date: 2026-03-31 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 创建 users 表
    op.create_table(
        'users',
        sa.Column('id', sa.String(32), primary_key=True),
        sa.Column('username', sa.String(64), unique=True, nullable=False),
        sa.Column('password_hash', sa.String(256), nullable=False),
        sa.Column('email', sa.String(256), nullable=True),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    op.create_index('idx_users_username', 'users', ['username'])
    op.create_index('idx_users_email', 'users', ['email'])
    
    # 2. 修改 orders 表
    # 2.1 添加 user_id 列（先允许nullable，然后回填数据后再设为not null）
    op.add_column('orders', sa.Column('user_id', sa.String(32), nullable=True))
    op.create_foreign_key(
        'fk_orders_user_id',
        'orders', 'users',
        ['user_id'], ['id']
    )
    
    # 2.2 删除 client_device_id 列和相关索引
    op.drop_index('idx_orders_device_id', table_name='orders')
    op.drop_column('orders', 'client_device_id')
    
    # 2.3 创建新的复合索引
    op.create_index(
        'idx_orders_user_plan_created',
        'orders',
        ['user_id', 'plan_id', 'created_at']
    )
    
    # 2.4 删除旧的复合索引
    op.drop_index('idx_orders_device_plan_created', table_name='orders')
    
    # 3. 修改 client_sessions 表
    # 3.1 添加 user_id 列
    op.add_column('client_sessions', sa.Column('user_id', sa.String(32), nullable=True))
    op.create_foreign_key(
        'fk_client_sessions_user_id',
        'client_sessions', 'users',
        ['user_id'], ['id']
    )
    
    # 3.2 修改 order_id 为 nullable
    op.alter_column('client_sessions', 'order_id',
                    existing_type=sa.String(32),
                    nullable=True)
    
    # 3.3 修改 marzban_username 为 nullable
    op.alter_column('client_sessions', 'marzban_username',
                    existing_type=sa.String(64),
                    nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 3. 恢复 client_sessions 表
    op.alter_column('client_sessions', 'marzban_username',
                    existing_type=sa.String(64),
                    nullable=False)
    op.alter_column('client_sessions', 'order_id',
                    existing_type=sa.String(32),
                    nullable=False)
    op.drop_constraint('fk_client_sessions_user_id', 'client_sessions', type_='foreignkey')
    op.drop_column('client_sessions', 'user_id')
    
    # 2. 恢复 orders 表
    op.create_index('idx_orders_device_plan_created', 'orders', 
                    ['client_device_id', 'plan_id', 'created_at'])
    op.drop_index('idx_orders_user_plan_created', table_name='orders')
    op.add_column('orders', sa.Column('client_device_id', sa.String(64), nullable=False))
    op.create_index('idx_orders_device_id', 'orders', ['client_device_id'])
    op.drop_constraint('fk_orders_user_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    
    # 1. 删除 users 表
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
