"""Add sweep_records table

Revision ID: 003
Revises: 002
Create Date: 2026-04-01 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # sweep_records table
    op.create_table(
        'sweep_records',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('address_id', sa.Integer, sa.ForeignKey('payment_addresses.id'), nullable=False),
        sa.Column('order_id', sa.String(32), sa.ForeignKey('orders.id'), nullable=True),
        sa.Column('chain', sa.String(20), nullable=False),
        sa.Column('asset_code', sa.String(20), nullable=False),
        sa.Column('from_address', sa.String(64), nullable=False),
        sa.Column('to_address', sa.String(64), nullable=False),
        sa.Column('amount', sa.Numeric(36, 18), nullable=False),
        sa.Column('amount_usd', sa.Numeric(10, 2), nullable=True),
        sa.Column('fee_amount', sa.Numeric(36, 18), nullable=True),
        sa.Column('fee_asset', sa.String(20), nullable=True),
        sa.Column('tx_hash', sa.String(128), unique=True, nullable=True),
        sa.Column('status', sa.String(20), default='pending', nullable=False),
        sa.Column('retry_count', sa.Integer, default=0),
        sa.Column('error_message', sa.String(512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    )
    
    # Indexes
    op.create_index('idx_sweep_records_address_id', 'sweep_records', ['address_id'])
    op.create_index('idx_sweep_records_order_id', 'sweep_records', ['order_id'])
    op.create_index('idx_sweep_records_chain', 'sweep_records', ['chain'])
    op.create_index('idx_sweep_records_from_address', 'sweep_records', ['from_address'])
    op.create_index('idx_sweep_records_tx_hash', 'sweep_records', ['tx_hash'])
    op.create_index('idx_sweep_records_status', 'sweep_records', ['status'])
    op.create_index('idx_sweep_records_status_created', 'sweep_records', ['status', 'created_at'])
    op.create_index('idx_sweep_records_address_status', 'sweep_records', ['address_id', 'status'])
    
    # Partial index for pending/retrying records (PostgreSQL specific)
    op.execute("""
        CREATE INDEX idx_sweep_records_pending 
        ON sweep_records (id) 
        WHERE status IN ('pending', 'retrying')
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sweep_records')
    # ### end Alembic commands ###
